// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentRecordApp.Entities;

#nullable disable

namespace StudentRecordApp.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentRecordApp.Entities.Program", b =>
                {
                    b.Property<string>("ProgramId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgramId");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            ProgramId = "CSI",
                            Name = "Computer Science"
                        },
                        new
                        {
                            ProgramId = "STA",
                            Name = "Statistics"
                        },
                        new
                        {
                            ProgramId = "HIS",
                            Name = "History"
                        },
                        new
                        {
                            ProgramId = "ENG",
                            Name = "English"
                        },
                        new
                        {
                            ProgramId = "FRE",
                            Name = "French"
                        });
                });

            modelBuilder.Entity("StudentRecordApp.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("ProgramId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentBirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StudentGPA")
                        .HasColumnType("float");

                    b.Property<string>("StudentLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            ProgramId = "FRE",
                            StudentBirthDate = "1/01/2000",
                            StudentFirstName = "John",
                            StudentGPA = 3.7999999999999998,
                            StudentLastName = "Doe"
                        },
                        new
                        {
                            StudentId = 2,
                            ProgramId = "STA",
                            StudentBirthDate = "15/05/1999",
                            StudentFirstName = "Jane",
                            StudentGPA = 3.5,
                            StudentLastName = "Smith"
                        },
                        new
                        {
                            StudentId = 3,
                            ProgramId = "HIS",
                            StudentBirthDate = "20/08/2001",
                            StudentFirstName = "Alice",
                            StudentGPA = 4.0,
                            StudentLastName = "Johnson"
                        },
                        new
                        {
                            StudentId = 4,
                            ProgramId = "ENG",
                            StudentBirthDate = "10/03/2002",
                            StudentFirstName = "Bob",
                            StudentGPA = 3.2000000000000002,
                            StudentLastName = "Williams"
                        },
                        new
                        {
                            StudentId = 5,
                            ProgramId = "CSI",
                            StudentBirthDate = "11/08/2003",
                            StudentFirstName = "Liam",
                            StudentGPA = 3.2000000000000002,
                            StudentLastName = "Knapp"
                        });
                });

            modelBuilder.Entity("StudentRecordApp.Entities.Student", b =>
                {
                    b.HasOne("StudentRecordApp.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId");

                    b.Navigation("Program");
                });
#pragma warning restore 612, 618
        }
    }
}
